// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCgFG0q02uzCGwSPsXgjv_BVaevKzhUls',
    appId: '1:1096954431507:web:1d1b4e20e2fe21ac9f57e6',
    messagingSenderId: '1096954431507',
    projectId: 'park-project-3cd64',
    authDomain: 'park-project-3cd64.firebaseapp.com',
    storageBucket: 'park-project-3cd64.appspot.com',
    measurementId: 'G-EKMEG3YGVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASuBwvSdO5A-YmZb8AmoniUBQ0RzMAaj4',
    appId: '1:1096954431507:android:303e3679f3904c939f57e6',
    messagingSenderId: '1096954431507',
    projectId: 'park-project-3cd64',
    storageBucket: 'park-project-3cd64.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfkGM8sRB58rQ5Kbu5_ELErz_xCO9PaJk',
    appId: '1:1096954431507:web:21a6f5cc932306fd9f57e6',
    messagingSenderId: '1096954431507',
    projectId: 'park-project-3cd64',
    authDomain: 'park-project-3cd64.firebaseapp.com',
    storageBucket: 'park-project-3cd64.appspot.com',
    measurementId: 'G-BLTG6KM741',
  );
}
